spring:
  datasource:
    url: ENC(KSvg4LgHCDd7HKXPVlXDBodobotDEUyNQfxl/CHsmy0TiAgKQDNUENVXJkHduzf5vr7tYJOzAHyGIGN2r6x4amtSe30+/omkYUFjIt6g074e1t+wSlgV+ILeNa/XsUxRBWC9cvJAeSfH0+VRHVM1aQ==)
    username: ENC(9aNi3IHj2H6kZr0ODNHtyA==)
#    password: ENC(9aNi3IHj2H6kZr0ODNHtyA==)
    password: ENC(TkOCIol7cpFd41MfpYYQBK+giiV3zOn3)
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:com/cj/sadmin/mapper/*.xml
zuul:
  num:  6
